#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CheckDatPlace.Resource", IsApplication=true)]

namespace CheckDatPlace
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int filterPlace = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080003
			public const int accent = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int divider = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int icons = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int primary = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int primary_dark = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int primary_light = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int primary_text = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int secondary_text = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int white = 2131230728;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addPlacesButton_states = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cameraButtonState = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CDPIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CircleButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CircleButtonNormal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CircleButtonPressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DefaultButton = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int DeletePlaceButton_states = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int filterButton_states = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int GPSButton = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int GPSButtonNormal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int GPSButtonPressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_add = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_add_black = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_camera = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_camera_black = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_filter = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_filter_black = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_location = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_location_2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_location_2_black = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_location_black = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_search = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_tick = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_action_tick_black = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_trash = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_trash_black = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int PrimaryColorBorder = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int showAllButton_states = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ValidateButton = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ValidateButtonNormal = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ValidateButtonPressed = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0009
			public const int AddPlaceButton = 2131361801;
			
			// aapt resource value: 0x7f0a000d
			public const int Heading = 2131361805;
			
			// aapt resource value: 0x7f0a0015
			public const int LoadingCircle = 2131361813;
			
			// aapt resource value: 0x7f0a0005
			public const int PlaceComment = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int PlaceGrade = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int PlaceName = 2131361792;
			
			// aapt resource value: 0x7f0a0012
			public const int SearchResultList = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int addPlaceButton = 2131361811;
			
			// aapt resource value: 0x7f0a0002
			public const int autoCompleteAddress = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int gpsButton = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int gpsProgressBar = 2131361796;
			
			// aapt resource value: 0x7f0a0008
			public const int horizontalImageViewer = 2131361800;
			
			// aapt resource value: 0x7f0a000a
			public const int imageViewerContainer = 2131361802;
			
			// aapt resource value: 0x7f0a000c
			public const int map = 2131361804;
			
			// aapt resource value: 0x7f0a0014
			public const int menu_DeleteImage = 2131361812;
			
			// aapt resource value: 0x7f0a0019
			public const int menu_Share = 2131361817;
			
			// aapt resource value: 0x7f0a0018
			public const int menu_ShowAll = 2131361816;
			
			// aapt resource value: 0x7f0a001a
			public const int menu_ShowMap = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int menu_camera = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int menu_deletePlace = 2131361820;
			
			// aapt resource value: 0x7f0a0001
			public const int placeTypeSpinner = 2131361793;
			
			// aapt resource value: 0x7f0a000e
			public const int placesListLayout = 2131361806;
			
			// aapt resource value: 0x7f0a0016
			public const int popFilterButton = 2131361814;
			
			// aapt resource value: 0x7f0a0011
			public const int popupFilterApplyButton = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int popupFilterRating = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int popupFilterSpinner = 2131361807;
			
			// aapt resource value: 0x7f0a0017
			public const int search = 2131361815;
			
			// aapt resource value: 0x7f0a000b
			public const int textView1 = 2131361803;
			
			// aapt resource value: 0x7f0a0007
			public const int viewerContainer = 2131361799;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreatePlaceLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageViewerLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MapViewLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlacesListCustomRowLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlacesListLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PopUpFilterLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SearchPlaceLayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int imageViewerMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int mapLayoutMenu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int searchMenu = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int updatePlaceLayoutMenu = 2131296259;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int SearchHint = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int SearchLabel = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int SearchTitle = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CDPTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
